spring.application.name=demo
server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/apirest
spring.datasource.username=root
spring.datasource.password=Biblio.123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
    #update: cada vez que levantamos la aplicación mira si existen o no las tablas. Si no existen las crea.
    #si cambio un campo en la tabla ejecuta un ALTER
    #create-drop: otro valor que elimina la tabla y la vuelve a crear
spring.jpa.show-sql=true
#Para que muestre las sentencias sql en los logs
spring.jpa.properties.hibernate.format_sql=true
